# Generated by Django 4.0.4 on 2022-06-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_paymentmodel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
